# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('code', models.CharField(max_length=10, verbose_name='编号')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 't_tag',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '小说', 'verbose_name_plural': '小说'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, height_field=120, null=True, upload_to='book/images', verbose_name='封面', width_field=80),
        ),
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.TextField(null=True, verbose_name='作品信息'),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.CharField(max_length=100, null=True, verbose_name='概要'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='t_book',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(null=True, to='content.Tag', verbose_name='标签'),
        ),
    ]
