# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20181204_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_height',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='高度'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_width',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_height', null=True, upload_to='book/images/', verbose_name='封面', width_field='cover_width'),
        ),
    ]
