# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20181204_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='content.Tag', verbose_name='标签'),
        ),
    ]
