# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('phone', models.CharField(max_length=12, verbose_name='电话')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('order_sn', models.CharField(max_length=20, verbose_name='订单号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额(元)')),
                ('pay_state', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '正在支付'), (3, '待退款'), (4, '已退款')], default=0, verbose_name='支付状态')),
                ('pay_type', models.IntegerField(choices=[(0, '余额'), (1, '网银'), (2, '支付宝'), (3, '微信')], default=0, verbose_name='支付类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Address', verbose_name='收货地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户订单',
                'verbose_name_plural': '用户订单',
                'db_table': 't_order',
            },
        ),
    ]
